services:
  db:
    image: postgres:15-alpine
    container_name: lms_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=lms_db
      - POSTGRES_USER=lms_user
      - POSTGRES_PASSWORD=lms_password
    networks:
      - lms_network

  web:
    build: .
    container_name: lms_web
    command: python manage.py runserver 0.0.0.0:8000
    dns: 8.8.8.8
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-key-lms-2026
      - DB_NAME=lms_db
      - DB_USER=lms_user
      - DB_PASS=lms_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - lms_network

volumes:
  postgres_data:

networks:
  lms_network:
    driver: bridge